<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mfrp</string>
		<string>emfrp</string>
		<string>￿</string>
	</array>
	<key>name</key>
	<string>Emfrp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*\n</string>
			<key>name</key>
			<string>comment.line.emfrp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Int|Char|Bool|Maybe|GF|Array|Float|Double|UInt|UChar|Long)\b</string>
			<key>name</key>
			<string>support.type.emfrp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(input|output|initialize|node|data|func|infix|infixl|infixr|if|then|else|match|as|type|ctype|lazy|init|skip|continue|@|-\&gt;|=&gt;)\b</string>
			<key>name</key>
			<string>keyword.control.emfrp</string>
		</dict>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>entity.name.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+(\.\d+)?</string>
			<key>name</key>
			<string>constant.numeric.emfrp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Z][a-zA-Z_]*</string>
			<key>name</key>
			<string>constant.other.emfrp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.emfrp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scope</key>
	<string>source.emfrp</string>
	<key>scopeName</key>
	<string>source.emfrp</string>
	<key>uuid</key>
	<string>10DEB276-75B2-457A-AF60-A48C4754207A</string>
</dict>
</plist>
